<?php

/**
* @see https://schema.org/Report
 * A Report generated by governmental or non-governmental organization.
*/

namespace Vnetby\Schemaorg\Types\Thing\CreativeWork\Article;

class Report extends \Vnetby\Schemaorg\Types\Thing\CreativeWork\Article\Article
{
   const TYPE = 'Report';

   /**
     * The number or other unique designator assigned to a Report by the publishing organization.
    * @var \Vnetby\Schemaorg\DataTypes\DataText
    */
   protected $prop_reportNumber;

   /**
     * The number or other unique designator assigned to a Report by the publishing organization.
    * @param \Vnetby\Schemaorg\DataTypes\DataText $value
    * @return static
    */
   function setReportNumber($value)
   {
       return $this->setProp('reportNumber', $value);
   }

   /**
     * The number or other unique designator assigned to a Report by the publishing organization.
    * @return \Vnetby\Schemaorg\DataTypes\DataText|null
    */
   function getReportNumber()
   {
       return $this->getProp('reportNumber');
   }
}
